name: "dashboard-project"

services:
  dashboard:
    image: ghcr.io/cambio-project/dispel-cockpit:1.3.0
    container_name: dashboard
    ports:
      - 8080:3000
    networks:
      - dashboardNetwork
    pull_policy: always
    depends_on:
      - mongo
    volumes:
      - ./data/simulations_results:/app/data/simulations_results
      - ./data/search_results:/app/data/search_results

  pspwizard:
    image: ghcr.io/cambio-project/pspwizardextended:1.1.0
    container_name: pspwizard
    ports:
      - 8081:8080
    networks:
      - dashboardNetwork
    pull_policy: always

  tqproprefiner:
    image: ghcr.io/cambio-project/transient-behavior-requirement-refiner:1.0.4
    container_name: tqproprefiner
    ports:
      - 8082:80
    networks:
      - dashboardNetwork
    pull_policy: always
    volumes:
      - ./data/simulations_results:/usr/share/nginx/html/assets/simulations_results
      - ./data/search_results:/usr/share/nginx/html/assets/search_results

  tbverifier:
    image: ghcr.io/cambio-project/transient-behavior-verifier:1.0.2
    container_name: tbverifier
    ports:
      - 8083:5000
    networks:
      - dashboardNetwork
    pull_policy: always
    volumes:
      - ./data/simulations_results:/app/simulations_results
      - ./data/search_results:/app/search_results

  misim:
    image: ghcr.io/cambio-project/misim:v4.1.4
    container_name: misim
    ports:
      - 8084:8080
    networks:
      - dashboardNetwork
    pull_policy: always
    volumes:
      - ./data/simulations_results:/simulations_results

  mosim:
    image: ghcr.io/cambio-project/mosim:0.3.5
    container_name: mosim
    ports:
      - 8087:8080
    networks:
      - dashboardNetwork
    pull_policy: always
    volumes:
      - ./data/search_results:/search_results

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    networks:
      - dashboardNetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 8085:27017

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - dashboardNetwork
    ports:
      - 8086:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo

networks:
  dashboardNetwork:
